version: 0.0
os: linux
files:
  - source: /  # Root of your GitHub repository
    destination: /Django_Chatapp  # Directly updating your existing app folder

permissions:
  - object: /Django_Chatapp
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/migrate_db.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
