version: 0.0
os: linux
files:
  - source: /  # This is the root of your GitHub repo
    destination: /Django_Chatapp  # This is where your app is already running

permissions:
  - object: /Django_Chatapp
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/migrate_db.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
