version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y git python3-venv python3-pip zip

  pre_build:
    commands:
      - git clone https://github.com/lalitt08/chatapp-project.git /Django_Chatapp
      - cd /Django_Chatapp
      - python3 -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Build phase completed successfully."

  post_build:
    commands:
      - echo "Packaging application into a ZIP file..."
      - cd ..
      - zip -r chatapp-build.zip Django_Chatapp

artifacts:
  files:
    - appspec.yml
    - Django_Chatapp/scripts/*
    - chatapp-build.zip
  discard-paths: no
