version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists and installing dependencies..."
      - apt-get update -y
      - apt-get install -y git python3-venv python3-pip zip  # Installing required dependencies

  pre_build:
    commands:
      - echo "Cloning the repository..."
      - git clone https://github.com/lalitt08/chatapp-project.git /Django_Chatapp

      - cd /Django_Chatapp

      - echo "Creating virtual environment..."
      - python3 -m venv venv

      - echo "Activating virtual environment..."
      - . venv/bin/activate  # Using '.' instead of 'source' for compatibility

      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Build phase completed successfully."

  post_build:
    commands:
      - echo "Packaging application into a ZIP file..."
      - cd ..
      - zip -r chatapp-build.zip Django_Chatapp

      - echo "Listing contents before zipping..."
      - ls -la Django_Chatapp  # Debugging step to verify the directory and contents

artifacts:
  files:
    - appspec.yml
    - chatapp-build.zip
  discard-paths: no
